[workspace]
members = [
    "crates/ice",
    "crates/rtc",
    "crates/turn",
    "data",
    "dtls",
    "rtcp",
    "rtp",
    "sctp",
    "sdp",
    "shared",
    "srtp",
    "stun",
]
resolver = "2"

[profile.dev]
opt-level = 0
