[workspace]
members = [
    "data",
    "dtls",
    "ice",
    "rtc",
    "rtcp",
    "rtp",
    "sctp",
    "sdp",
    "shared",
    "srtp",
    "stun",
    "turn",
]
resolver = "2"

[profile.dev]
opt-level = 0
