[package]
name = "rtc"
version = "0.0.2"
edition = "2021"
authors = ["Rain Liu <y@liu.x>"]
description = "RTC in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rtc"
repository = "https://github.com/ngr-tc/rtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
