[workspace]
members = [
    "data",
    "rtc-dtls",
    "rtc",
    "rtcp",
    "rtp",
    "sctp",
    "rtc-sdp",
    "rtc-shared",
    "srtp",
    "rtc-stun",
]
resolver = "2"

[profile.dev]
opt-level = 0
