[package]
name = "rtc-sdp"
version = "0.1.1"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "RTC SDP in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rtc-sdp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/rtc"

[dependencies]
url = "2"
rand = "0.8"
thiserror = "1"
substring = "1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false
