[package]
name = "hub"
version = "0.0.0"
edition = "2021"

[dependencies]
util = { version = "0.7.0", package = "webrtc-util", default-features = false, features = ["conn"] }
shared = { path = "../../../shared", package = "shared", default-features = false, features = [] }
dtls = { package = "dtls", path = "../../" }

tokio = { version = "1", features = ["full"] }
rcgen = { version = "0.10", features = ["pem", "x509-parser"] }
rustls = "0.19"
thiserror = "1"
