[package]
name = "rtc-shared"
version = "0.1.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "RTC Shared in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rtc-shared"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/rtc"

[features]
default = ["crypto", "marshal", "replay"]
crypto = []
marshal = []
replay = []

[dependencies]
thiserror = "1"
bytes = "1.4"
aes-gcm = { version = "0.10", features = ["std"] }
url = "2.2"
rcgen = "0.12"
sec1 = { version = "0.7", features = ["std"] }
p256 = { version = "0.13", features = ["default", "ecdh", "ecdsa"] }
aes = "0.8"
