[package]
name = "rtc-datachannel"
version = "0.1.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "RTC DataChannel in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rtc-datachannel"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/rtc"

[dependencies]
shared = { version = "0.2.0", path = "../rtc-shared", package = "rtc-shared", default-features = false, features = ["marshal"] }
sctp = { version = "0.1", path = "../rtc-sctp", package = "rtc-sctp" }

bytes = "1"
log = "0.4"
thiserror = "1"

[dev-dependencies]
env_logger = "0.11"
chrono = "0.4.34"
