[package]
name = "turn"
version = "0.0.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "TURN in Rust"
license = "MIT/Apache-2.0"

[dependencies]
shared = { path = "../shared", package = "shared", default-features = false, features = [] }
stun = { path = "../stun", package = "stun" }

util = { version = "0.7.0", package = "webrtc-util", default-features = false, features = ["conn", "vnet"] }


futures = "0.3.21"
tokio = { version = "1.19", features = ["full"] }
async-trait = "0.1.56"
log = "0.4.16"
base64 = "0.21.2"
rand = "0.8.5"
ring = "0.16.20"
md-5 = "0.10.1"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4.0" # must match the min version of the `tokio` crate above
env_logger = "0.9.0"
chrono = "0.4.23"
hex = "0.4.3"
clap = "3.2.6"
criterion = "0.4.0"

[features]
metrics = []

[[bench]]
name = "bench"
harness = false

[[example]]
name = "turn_client_udp"
path = "examples/turn_client_udp.rs"
bench = false
